version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.7.0
    steps:
      - checkout
      - run:
          name: npm install
          command: npm install
      - run:
          name: stylelint
          command: ./node_modules/stylelint/bin/stylelint.js src/stylesheets/**/**/*
      - run:
          name: tslint
          command: ./node_modules/tslint/bin/tslint src/typescripts/**/**/*
